import Link from "next/link";
import { Reveal, RevealItem, RevealStagger } from "./Reveal";
import { services } from "@/lib/services-data";
import { ServiceIcon, ArrowIcon } from "./visuals/Icons";

const groups = [
  { label: "DIGITAL", title: "Software that moves the business.", filter: ["web", "app", "design"] },
  { label: "INFRASTRUCTURE", title: "The systems underneath it all.", filter: ["domain", "network", "office"] },
  { label: "SECURITY + SUPPORT", title: "Keep it visible. Keep it running.", filter: ["cctv", "amc"] },
];

export function Services() {
  return <section id="services" className="py-32"><div className="max-w-[1240px] mx-auto px-6 md:px-8"><Reveal><span className="font-mono text-[10px] tracking-[.16em] uppercase text-orange">Capabilities</span><h2 className="mt-4 max-w-[760px] font-display font-bold tracking-[-.035em] text-[clamp(36px,5vw,62px)] leading-[1.02]">A connected technology stack, not a pile of vendors.</h2><p className="mt-6 max-w-[650px] text-mid text-[16px] leading-[1.7]">From the first line of code to the network cable in the wall, CordIQ gives growing teams one place to build, secure and maintain their technology.</p></Reveal><div className="mt-16 space-y-5">{groups.map((g)=><Reveal key={g.label} y={28}><div className="grid lg:grid-cols-[.55fr_1.2fr] gap-7 border-t border-line pt-7"><div><span className="font-mono text-[10px] tracking-[.15em] text-low">{g.label}</span><h3 className="mt-3 font-display font-semibold text-2xl">{g.title}</h3></div><RevealStagger className="grid sm:grid-cols-3 gap-3">{g.filter.map(slug=>{const s=services.find(x=>x.icon===slug); if(!s)return null; const Icon=ServiceIcon[s.icon]; return <RevealItem key={s.slug}><Link href={`/services/${s.slug}`} className="group block h-full rounded-2xl border border-line bg-bg1/70 p-6 hover:border-violetSoft hover:-translate-y-1 transition-all"><span className="w-14 h-14 rounded-2xl bg-orange/10 flex items-center justify-center text-orange"><Icon className="w-6 h-6"/></span><h4 className="mt-6 font-semibold text-lg">{s.navLabel}</h4><p className="mt-2 text-sm text-mid leading-relaxed">{s.navBlurb}</p><span className="mt-5 inline-flex items-center gap-1.5 text-sm font-semibold text-orange">Learn more<ArrowIcon className="w-3.5 h-3.5 transition-transform group-hover:translate-x-1"/></span></Link></RevealItem>})}</RevealStagger></div></Reveal>)}</div><Reveal y={28} className="mt-7"><Link href="/services" className="group flex flex-col sm:flex-row sm:items-center justify-between gap-6 rounded-2xl bg-hi text-bg0 p-8 hover:-translate-y-1 transition-all"><div className="flex items-center gap-5"><span className="w-14 h-14 rounded-2xl bg-bg0/10 flex items-center justify-center flex-shrink-0"><ArrowIcon className="w-6 h-6"/></span><div><h4 className="font-semibold text-lg">See all services</h4><p className="mt-1 text-sm opacity-70">AI integration, workflow automation and more — explore the full list.</p></div></div><span className="inline-flex items-center gap-1.5 text-sm font-semibold flex-shrink-0">View services<ArrowIcon className="w-3.5 h-3.5 transition-transform group-hover:translate-x-1"/></span></Link></Reveal></div></section>;
}
